site_name: xkcd936
site_description: Convert cumbersome strings into memorable phrases

theme:
  name: "material"

repo_name: rayraegah/xkcd936
repo_url: https://github.com/rayraegah/xkcd936
edit_uri: ""

nav:
  - Introduction: "index.md"
  - How It Works: "how-it-works.md"
  - Release Notes: "release-notes.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
